from __future__ import annotations

DAYS = [
    "Lunedi",
    "Martedi",
    "Mercoledi",
    "Giovedi",
    "Venerdi",
    "Sabato",
    "Domenica",
]

CUISINE_OPTIONS = [
    "Italiana",
    "Mediterranea",
    "Tradizione regionale",
    "Comfort food leggera",
    "Bowl proteiche",
    "Medio Oriente",
    "Tex-Mex",
    "Indiana",
    "Asiatica",
]

PANTRY_OPTIONS = [
    "Avena",
    "Riso",
    "Pasta",
    "Farro",
    "Orzo",
    "Legumi in barattolo",
    "Pomodori pelati",
    "Uova",
    "Yogurt greco",
    "Frutta secca",
    "Pane integrale",
    "Formaggi freschi",
]

BREAKFAST_TEMPLATES = [
    {
        "shared_base": "Pane integrale tostato con ricotta, miele e pera",
        "omnivore_title": "Toast con ricotta, miele e pera",
        "vegetarian_title": "Toast con ricotta, miele e pera",
        "description": "Colazione semplice in stile italiano, pronta in pochi minuti e facile da ripetere.",
        "ingredients": ["pane integrale", "ricotta", "miele", "pera", "noci"],
        "prep_notes": "Tosta il pane e completa con ricotta e frutta a fette.",
        "shopping": {
            "Colazione": ["pane integrale", "ricotta", "miele", "pere", "noci"],
        },
        "prep_minutes": 5,
        "budget_tier": "Bilanciato",
        "cuisines": ["Italiana", "Comfort food leggera"],
    },
    {
        "shared_base": "Yogurt greco con mela, mandorle e cannella",
        "omnivore_title": "Coppa di yogurt greco, mela e mandorle",
        "vegetarian_title": "Coppa di yogurt greco, mela e mandorle",
        "description": "Una colazione fresca e italiana nella combinazione di ingredienti, con prep quasi nullo.",
        "ingredients": ["yogurt greco", "mela", "mandorle", "cannella"],
        "prep_notes": "Taglia la mela al momento e aggiungi mandorle e cannella.",
        "shopping": {
            "Colazione": ["yogurt greco", "mele", "mandorle", "cannella"],
        },
        "prep_minutes": 4,
        "budget_tier": "Essenziale",
        "cuisines": ["Italiana", "Mediterranea"],
    },
    {
        "shared_base": "Fette biscottate integrali con ricotta e confettura senza zuccheri aggiunti",
        "omnivore_title": "Fette biscottate con ricotta e confettura",
        "vegetarian_title": "Fette biscottate con ricotta e confettura",
        "description": "Una colazione casalinga classica, facile da tenere in rotazione per tutta la settimana.",
        "ingredients": ["fette biscottate integrali", "ricotta", "confettura di albicocche", "kiwi"],
        "prep_notes": "Spalma ricotta e confettura al momento e accompagna con frutta fresca.",
        "shopping": {
            "Colazione": ["fette biscottate integrali", "ricotta", "confettura di albicocche", "kiwi"],
        },
        "prep_minutes": 4,
        "budget_tier": "Essenziale",
        "cuisines": ["Italiana", "Tradizione regionale"],
    },
    {
        "shared_base": "Ricotta montata con cacao amaro, fragole e nocciole",
        "omnivore_title": "Ciotola di ricotta, cacao e fragole",
        "vegetarian_title": "Ciotola di ricotta, cacao e fragole",
        "description": "Una colazione dal profilo piu ricco, ma ancora ancorata a ingredienti italiani semplici.",
        "ingredients": ["ricotta", "fragole", "nocciole", "cacao amaro"],
        "prep_notes": "Lavora la ricotta con poco cacao e completa con frutta e granella.",
        "shopping": {
            "Colazione": ["ricotta", "fragole", "nocciole", "cacao amaro"],
        },
        "prep_minutes": 6,
        "budget_tier": "Premium",
        "cuisines": ["Italiana", "Comfort food leggera"],
    },
    {
        "shared_base": "Pane integrale con yogurt scolato, miele e albicocche",
        "omnivore_title": "Crostoni dolci con yogurt e albicocche",
        "vegetarian_title": "Crostoni dolci con yogurt e albicocche",
        "description": "Versione italiana e leggera della colazione con pane e topping cremoso.",
        "ingredients": ["pane integrale", "yogurt greco", "albicocche", "miele", "mandorle"],
        "prep_notes": "Tosta il pane, spalma yogurt denso e aggiungi frutta e miele.",
        "shopping": {
            "Colazione": ["pane integrale", "yogurt greco", "albicocche", "miele", "mandorle"],
        },
        "prep_minutes": 5,
        "budget_tier": "Bilanciato",
        "cuisines": ["Italiana", "Mediterranea"],
    },
]

LUNCH_BLUEPRINTS = [
    {
        "name": "Insalata di farro mediterranea",
        "shared_base": "Insalata di {grain} con pomodorini, zucchine grigliate e basilico",
        "title_template": "Insalata di {grain} con {protein}",
        "omnivore_description": "Pranzo freddo all'italiana, pensato per essere saziante ma rapido da assemblare.",
        "vegetarian_description": "Versione vegetariana con la stessa struttura mediterranea e zero cotture complesse.",
        "grain_options": ["farro", "orzo", "riso"],
        "base_ingredients": ["pomodorini", "zucchine grigliate", "basilico", "olio evo"],
        "omnivore_options": ["pollo arrosto", "uova sode", "tonno al naturale"],
        "vegetarian_options": ["ceci", "ricotta", "mozzarella"],
        "prep_notes": "Usa verdure gia cotte e completa il piatto in una sola ciotola.",
        "prep_minutes": 10,
        "budget_tier": "Bilanciato",
        "cuisines": ["Italiana", "Mediterranea", "Bowl proteiche"],
    },
    {
        "name": "Piadina romagnola integrale",
        "shared_base": "Piadina romagnola integrale con verdure grigliate e insalata croccante",
        "title_template": "Piadina con {protein}",
        "omnivore_description": "Pranzo veloce da stile tavola fredda italiana, con ingredienti facili da tenere pronti.",
        "vegetarian_description": "Stessa linea di montaggio della piadina, ma con farcitura vegetariana proteica.",
        "grain_options": [],
        "base_ingredients": ["piadina integrale", "verdure grigliate", "insalata", "pomodoro"],
        "omnivore_options": ["tacchino arrosto", "uova sode"],
        "vegetarian_options": ["cannellini schiacciati", "ricotta", "primo sale"],
        "prep_notes": "Scalda appena la piadina, poi assembla il ripieno in 5 minuti.",
        "prep_minutes": 9,
        "budget_tier": "Bilanciato",
        "cuisines": ["Italiana", "Comfort food leggera", "Bowl proteiche"],
    },
    {
        "name": "Pasta fredda alla caprese",
        "shared_base": "Pasta fredda con pomodorini, basilico e condimento leggero",
        "title_template": "Pasta fredda con {protein}",
        "omnivore_description": "Una pasta fredda italiana da preparare in anticipo e rifinire al momento.",
        "vegetarian_description": "Versione vegetariana con la stessa base caprese e un profilo piu fresco.",
        "grain_options": ["pasta"],
        "base_ingredients": ["pomodorini", "basilico", "olio evo"],
        "omnivore_options": ["pollo alla piastra", "tonno al naturale"],
        "vegetarian_options": ["mozzarella", "ceci", "ricotta salata"],
        "prep_notes": "Condisci a freddo e aggiungi il basilico all'ultimo per mantenerlo profumato.",
        "prep_minutes": 12,
        "budget_tier": "Premium",
        "cuisines": ["Italiana", "Mediterranea", "Comfort food leggera"],
    },
    {
        "name": "Insalata di riso italiana",
        "shared_base": "Insalata di {grain} con verdure croccanti, prezzemolo e condimento leggero",
        "title_template": "Insalata di {grain} con {protein}",
        "omnivore_description": "Una lunch box italiana molto pratica, con ingredienti da dispensa e frigo.",
        "vegetarian_description": "Versione vegetariana con legumi o formaggio fresco, pensata per restare semplice.",
        "grain_options": ["riso", "orzo"],
        "base_ingredients": ["carote", "zucchine", "prezzemolo", "olio evo"],
        "omnivore_options": ["uova sode", "tonno al naturale"],
        "vegetarian_options": ["ceci", "primo sale", "cannellini"],
        "prep_notes": "Cuoci il cereale in batch e condisci con ingredienti gia porzionati.",
        "prep_minutes": 10,
        "budget_tier": "Essenziale",
        "cuisines": ["Italiana", "Mediterranea", "Bowl proteiche"],
    },
]

DINNER_BLUEPRINTS = [
    {
        "name": "Teglia al limone e rosmarino",
        "shared_base": "Teglia all'italiana con patate, zucchine e limone al rosmarino",
        "omnivore": {
            "title": "Pollo al limone e rosmarino",
            "description": "Una teglia unica, molto italiana nei profumi, pensata per sporcare il meno possibile.",
            "ingredients": ["petto di pollo", "zucchine", "patate", "limone", "rosmarino"],
            "prep_notes": "Condisci tutto in una bowl e inforna in un'unica teglia.",
        },
        "vegetarian": {
            "title": "Ceci croccanti e primo sale al limone",
            "description": "La stessa teglia resta valida per entrambi, con finitura vegetariana semplice e italiana.",
            "ingredients": ["ceci", "primo sale", "zucchine", "patate", "limone", "rosmarino"],
            "prep_notes": "Aggiungi il primo sale negli ultimi minuti per mantenerlo morbido.",
        },
        "prep_minutes": 30,
        "leftover_friendly": True,
        "reuse_from_previous": "Cuoci doppia dose di verdure per i bowl del giorno dopo.",
        "kitchen_load": "Basso",
        "shopping": {
            "Verdure": ["zucchine", "patate", "limoni", "rosmarino"],
            "Proteine": ["petto di pollo", "ceci", "primo sale"],
            "Dispensa": ["olio evo"],
        },
        "budget_tier": "Bilanciato",
        "cuisines": ["Italiana", "Mediterranea", "Bowl proteiche"],
    },
    {
        "name": "Pasta e lenticchie",
        "shared_base": "Pasta e lenticchie al rosmarino con passata leggera",
        "omnivore": {
            "title": "Pasta e lenticchie con uovo morbido",
            "description": "Una ricetta italiana molto concreta, economica e adatta a una cena confortante.",
            "ingredients": ["pasta corta", "lenticchie", "passata di pomodoro", "rosmarino", "uova"],
            "prep_notes": "Lessa l'uovo a parte negli ultimi minuti e servilo sulla minestra.",
        },
        "vegetarian": {
            "title": "Pasta e lenticchie con ricotta al limone",
            "description": "La stessa base viene completata con una finitura vegetariana molto italiana e delicata.",
            "ingredients": ["pasta corta", "lenticchie", "passata di pomodoro", "rosmarino", "ricotta", "limone"],
            "prep_notes": "Aggiungi la ricotta a cucchiaiate a fuoco spento.",
        },
        "prep_minutes": 30,
        "leftover_friendly": True,
        "reuse_from_previous": "Cuoci una porzione abbondante per trasformarla in lunch box del giorno seguente.",
        "kitchen_load": "Basso",
        "shopping": {
            "Verdure": ["limoni", "rosmarino"],
            "Proteine": ["uova", "ricotta", "lenticchie"],
            "Dispensa": ["pasta corta", "passata di pomodoro"],
        },
        "budget_tier": "Essenziale",
        "cuisines": ["Italiana", "Comfort food leggera", "Tradizione regionale"],
    },
    {
        "name": "Polpette al sugo",
        "shared_base": "Polpette al sugo leggero con bieta saltata e pane tostato",
        "omnivore": {
            "title": "Polpette di tacchino al sugo",
            "description": "Una cena italiana classica, alleggerita ma ancora molto riconoscibile.",
            "ingredients": ["macinato di tacchino", "passata di pomodoro", "bieta", "pane integrale", "parmigiano"],
            "prep_notes": "Forma le polpette in anticipo e finisci la cottura nel sugo.",
        },
        "vegetarian": {
            "title": "Polpette di ricotta e spinaci al sugo",
            "description": "Stessa atmosfera della ricetta italiana classica, con variante vegetariana semplice.",
            "ingredients": ["ricotta", "spinaci", "passata di pomodoro", "bieta", "pane integrale", "parmigiano"],
            "prep_notes": "Compatta l'impasto con poco pane grattugiato e cuoci dolcemente nel sugo.",
        },
        "prep_minutes": 30,
        "leftover_friendly": True,
        "reuse_from_previous": "Conserva polpette e sugo per un pranzo rapido con pane o cereale gia cotto.",
        "kitchen_load": "Medio",
        "shopping": {
            "Verdure": ["bieta", "spinaci"],
            "Proteine": ["macinato di tacchino", "ricotta", "parmigiano"],
            "Dispensa": ["passata di pomodoro", "pane integrale"],
        },
        "budget_tier": "Bilanciato",
        "cuisines": ["Italiana", "Comfort food leggera", "Tradizione regionale"],
    },
    {
        "name": "Piadina romagnola",
        "shared_base": "Piadina romagnola integrale con verdure grigliate e crema morbida",
        "omnivore": {
            "title": "Piadina con pollo arrosto e robiola",
            "description": "Una cena italiana molto pratica, con montaggio al tavolo e tempi ridotti.",
            "ingredients": ["piadina integrale", "pollo arrosto", "zucchine grigliate", "robiola", "insalata"],
            "prep_notes": "Scalda appena la piadina e assembla il ripieno al momento.",
        },
        "vegetarian": {
            "title": "Piadina con cannellini e robiola",
            "description": "Versione vegetariana romagnola nella struttura, con ripieno morbido e proteico.",
            "ingredients": ["piadina integrale", "cannellini", "zucchine grigliate", "robiola", "insalata"],
            "prep_notes": "Schiaccia i cannellini con poco olio evo e farcisci la piadina.",
        },
        "prep_minutes": 20,
        "leftover_friendly": False,
        "reuse_from_previous": "Riusa le verdure grigliate gia cotte nel batch cooking.",
        "kitchen_load": "Basso",
        "shopping": {
            "Verdure": ["zucchine", "insalata"],
            "Proteine": ["pollo arrosto", "cannellini", "robiola"],
            "Dispensa": ["piadina integrale"],
        },
        "budget_tier": "Bilanciato",
        "cuisines": ["Italiana", "Tradizione regionale", "Bowl proteiche"],
    },
    {
        "name": "Insalata di farro",
        "shared_base": "Insalata di farro con pomodorini, basilico e verdure grigliate",
        "omnivore": {
            "title": "Farro all'italiana con pollo al basilico",
            "description": "Una bowl in chiave italiana, leggera ma concreta e facile da replicare.",
            "ingredients": ["farro", "pollo alla piastra", "pomodorini", "zucchine grigliate", "basilico"],
            "prep_notes": "Cuoci il farro in anticipo e condisci tutto a temperatura ambiente.",
        },
        "vegetarian": {
            "title": "Farro all'italiana con ceci e primo sale",
            "description": "Stessa base mediterranea con una finitura vegetariana molto semplice.",
            "ingredients": ["farro", "ceci", "primo sale", "pomodorini", "zucchine grigliate", "basilico"],
            "prep_notes": "Aggiungi il primo sale solo alla fine per tenerlo compatto.",
        },
        "prep_minutes": 20,
        "leftover_friendly": True,
        "reuse_from_previous": "Prepara farro extra per uno o due pranzi freddi.",
        "kitchen_load": "Basso",
        "shopping": {
            "Verdure": ["pomodorini", "zucchine", "basilico"],
            "Proteine": ["pollo alla piastra", "ceci", "primo sale"],
            "Dispensa": ["farro"],
        },
        "budget_tier": "Essenziale",
        "cuisines": ["Italiana", "Mediterranea", "Bowl proteiche"],
    },
    {
        "name": "Minestrone di cannellini",
        "shared_base": "Minestrone rustico di cannellini con crostini al forno",
        "omnivore": {
            "title": "Minestrone con uovo barzotto e pepe",
            "description": "Una cena italiana di conforto, costruita su dispensa e verdure di base.",
            "ingredients": ["cannellini", "carote", "sedano", "cipolla", "pomodori", "uova", "pane casereccio"],
            "prep_notes": "Cuoci l'uovo negli ultimi minuti e servi con crostini caldi.",
        },
        "vegetarian": {
            "title": "Minestrone con cannellini e parmigiano",
            "description": "Versione vegetariana dello stesso piatto, con struttura molto tradizionale.",
            "ingredients": ["cannellini", "carote", "sedano", "cipolla", "pomodori", "parmigiano", "pane casereccio"],
            "prep_notes": "Completa con parmigiano grattugiato e crostini al forno.",
        },
        "prep_minutes": 25,
        "leftover_friendly": True,
        "reuse_from_previous": "Cuoci doppia zuppa per uno o due pranzi veloci.",
        "kitchen_load": "Basso",
        "shopping": {
            "Verdure": ["carote", "sedano", "cipolla", "pomodori"],
            "Proteine": ["cannellini", "uova", "parmigiano"],
            "Dispensa": ["pane casereccio"],
        },
        "budget_tier": "Essenziale",
        "cuisines": ["Italiana", "Comfort food leggera", "Tradizione regionale"],
    },
    {
        "name": "Tortino al forno",
        "shared_base": "Tortino al forno di zucchine e patate con insalata fresca",
        "omnivore": {
            "title": "Tortino con tacchino arrosto a lato",
            "description": "Una cena italiana da forno, semplice da organizzare anche nei giorni pieni.",
            "ingredients": ["uova", "zucchine", "patate", "parmigiano", "tacchino arrosto"],
            "prep_notes": "Inforna il tortino e aggiungi il tacchino solo al servizio.",
        },
        "vegetarian": {
            "title": "Tortino con ceci al limone",
            "description": "La stessa base al forno viene servita con ceci per una variante vegetariana pulita.",
            "ingredients": ["uova", "zucchine", "patate", "parmigiano", "ceci", "limone"],
            "prep_notes": "Condisci i ceci separatamente e servili accanto al tortino.",
        },
        "prep_minutes": 25,
        "leftover_friendly": True,
        "reuse_from_previous": "Il tortino avanzato si puo riusare freddo a pranzo con un'insalata.",
        "kitchen_load": "Basso",
        "shopping": {
            "Verdure": ["zucchine", "patate", "limoni", "insalata"],
            "Proteine": ["uova", "tacchino arrosto", "ceci", "parmigiano"],
        },
        "budget_tier": "Essenziale",
        "cuisines": ["Italiana", "Comfort food leggera"],
    },
    {
        "name": "Gnocchi alla sorrentina",
        "shared_base": "Gnocchi alla sorrentina leggeri con pomodoro e basilico",
        "omnivore": {
            "title": "Gnocchi alla sorrentina con pollo al basilico",
            "description": "Una ricetta italiana molto riconoscibile, alleggerita ma ancora appagante.",
            "ingredients": ["gnocchi", "passata di pomodoro", "mozzarella", "basilico", "pollo alla piastra"],
            "prep_notes": "Gratina brevemente e servi con il pollo gia affettato.",
        },
        "vegetarian": {
            "title": "Gnocchi alla sorrentina con melanzane grigliate",
            "description": "La variante vegetariana resta perfettamente italiana e sfrutta lo stesso sugo.",
            "ingredients": ["gnocchi", "passata di pomodoro", "mozzarella", "basilico", "melanzane grigliate"],
            "prep_notes": "Griglia le melanzane prima oppure usale dal batch cooking.",
        },
        "prep_minutes": 25,
        "leftover_friendly": False,
        "reuse_from_previous": "Riusa il sugo al pomodoro avanzato per un pranzo espresso il giorno dopo.",
        "kitchen_load": "Medio",
        "shopping": {
            "Verdure": ["basilico", "melanzane"],
            "Proteine": ["pollo alla piastra", "mozzarella"],
            "Dispensa": ["gnocchi", "passata di pomodoro"],
        },
        "budget_tier": "Premium",
        "cuisines": ["Italiana", "Tradizione regionale", "Comfort food leggera"],
    },
    {
        "name": "Orzotto ai funghi",
        "shared_base": "Orzotto ai funghi e piselli con prezzemolo",
        "omnivore": {
            "title": "Orzotto ai funghi con straccetti di tacchino",
            "description": "Un piatto unico molto italiano nell'impostazione, con profilo piu elegante ma gestibile.",
            "ingredients": ["orzo", "funghi", "piselli", "prezzemolo", "tacchino"],
            "prep_notes": "Cuoci l'orzo come un risotto rapido e aggiungi il tacchino rosolato alla fine.",
        },
        "vegetarian": {
            "title": "Orzotto ai funghi con cannellini",
            "description": "Stessa base cremosa, completata in chiave vegetariana con legumi molto semplici.",
            "ingredients": ["orzo", "funghi", "piselli", "prezzemolo", "cannellini"],
            "prep_notes": "Aggiungi i cannellini gia cotti negli ultimi minuti.",
        },
        "prep_minutes": 30,
        "leftover_friendly": True,
        "reuse_from_previous": "L'orzo avanzato si compatta bene e resta valido come schiscetta del giorno dopo.",
        "kitchen_load": "Medio",
        "shopping": {
            "Verdure": ["funghi", "piselli", "prezzemolo"],
            "Proteine": ["tacchino", "cannellini"],
            "Dispensa": ["orzo"],
        },
        "budget_tier": "Premium",
        "cuisines": ["Italiana", "Tradizione regionale", "Mediterranea"],
    },
    {
        "name": "Pasta al forno di chiusura",
        "shared_base": "Pasta al forno leggera con sugo avanzato e mozzarella",
        "omnivore": {
            "title": "Pasta al forno con ragu di tacchino",
            "description": "Chiusura della settimana in stile italiano, pensata per recuperare basi e sughi gia pronti.",
            "ingredients": ["pasta", "ragu di tacchino", "mozzarella", "spinaci"],
            "prep_notes": "Assembla in pirofila e gratina senza ulteriori preparazioni.",
        },
        "vegetarian": {
            "title": "Pasta al forno con ragu di lenticchie",
            "description": "La variante vegetariana recupera lo stesso formato comfort della teglia finale.",
            "ingredients": ["pasta", "ragu di lenticchie", "mozzarella", "spinaci"],
            "prep_notes": "Aggiungi un mestolo d'acqua per mantenerla cremosa in forno.",
        },
        "prep_minutes": 20,
        "leftover_friendly": True,
        "reuse_from_previous": "Recupera sughi e verdure residue per svuotare il frigo.",
        "kitchen_load": "Basso",
        "shopping": {
            "Frigo": ["mozzarella"],
            "Verdure": ["spinaci"],
            "Dispensa": ["pasta"],
        },
        "budget_tier": "Bilanciato",
        "cuisines": ["Italiana", "Comfort food leggera", "Tradizione regionale"],
    },
]